### PR TITLE
Russian localisation

### PR DESCRIPTION
**Pull request by Atla01**
Translation of the entire mod, except for its configuration. If anything other than the configuration isn't translated, it's probably just because it wasn't possible.

### CODE REVIEW

**Comment by Atla01** [comment]
I understand I won't be able to see some of the changes as they will be created for a future version. Because of this I can't test the new features, but it's minor things, I'll translate it later. Looking forward to updates, the mod is good.

**Comment by Sweenus** [comment]
Thank you for your continued work!
The final changes on my end should be completed within the next two weeks. I'll keep you updated 🙂

**Comment by Sweenus** [comment]
Hey Atla!
The last commit I made should be the final one.
Once you've updated the PR I'll go ahead and merge so it's ready for release in a few days 🙂

**Comment by Sweenus** [comment]
Thank you so much for getting that updated for the release version! You are awesome 🙂

**Pull request merged**
