### PR TITLE
easier translations

### PR DESCRIPTION
**Pull request by MrOz59**
I just changed the skill definitions file to support multiple translations, so it's easier to translate into any language, I'll do a translation for pt_br if this modification is approved

### CODE REVIEW

**Review by Sweenus — APPROVED** [review]

**Comment by Sweenus** [comment]
Wow, I had no idea jsons could be translated in this way. This is incredibly helpful - thank you so much!

**Comment by MrOz59** [comment]
> Wow, I had no idea jsons could be translated in this way. This is incredibly helpful - thank you so much!

It is possible, as long as it is inside a jar file, if the datapack was in zip format, it would not work

**Comment by MrOz59** [comment]
I would like to know, if you would allow me to post a version of your mod, in which I only modified the datapack to work with the paragliders mod, I tried to make this modification via datapack, but it only works if it is in zip, if it is in jar, the original has priority and the change is not applied, so I can't do the translations, I'm not distributing the mod itself, it goes with my modpack

**Comment by Sweenus** [comment]
Sorry for the delay!
Do you mean that when trying to bundle a datapack in the modpack, it is for some reason not applying?
Datapacks should work fine for overiding Simply Skills skill trees, but I've never tested in a modpack.

If absolutely necessary, you have my permission to bundle your modified version of Simply Skills within your modpack itself. I would just ask that you don't repost/redistribute the mod in any other way.

**Comment by MrOz59** [comment]
> Sorry for the delay! Do you mean that when trying to bundle a datapack in the modpack, it is for some reason not applying? Datapacks should work fine for overiding Simply Skills skill trees, but I've never tested in a modpack.
> 
> If absolutely necessary, you have my permission to bundle your modified version of Simply Skills within your modpack itself. I would just ask that you don't repost/redistribute the mod in any other way.

Thank you very much, Explanation:
When my datapack is in ZIP format everything works fine, but I can't use TRANSLATE in JSON files, so I changed the datapack to JAR, but I think that due to the order in which the loader loads the mods it doesn't apply the modifications, at least that's what I believe, so I changed it directly in the mod's original datapack, this solved my problem, but because of the mod's license, Curseforge doesn't allow me to upload the modpack

**Comment by Sweenus** [comment]
Hey @MrOz59 👋 
I've pushed a version live with the translation changes you've made - again, thank you so much for this contribution!
Did you end up making a pt_br translation?

**Comment by MrOz59** [comment]
I got overwhelmed with my new job, I also started a new personal project, so I ended up running out of free time to work on the translation, so I haven't been able to finish it yet

**Comment by Sweenus** [comment]
> I got overwhelmed with my new job, I also started a new personal project, so I ended up running out of free time to work on the translation, so I haven't been able to finish it yet

No worries! I totally understand if you don't have the time.
Your existing contribution is already hugely helpful and appreciated 🙂

**Pull request merged**
